schema = {
    "type": "string",
    "$id": "#dai",
    "enum": [
      "aaa - day, month and year are accurate",
      "aae - day and month are accurate, year is estimated",
      "aau - day and month are accurate, year is unknown",
      "aee - day is accurate, month and year are estimated",
      "aeu - day is accurate, month is estimated, year is unknown",
      "auu - day is accurate, month and year are unknown",
      "aua - day is accurate, month is unknown, year is accurate",
      "aue - day is accurate, month is unknown, year is estimated",
      "aea - day is accurate, month is estimated, year is accurate",
      "eaa - day is estimated, month and year are accurate",
      "eae - day is estimated, month is accurate, year is estimated",
      "eau - day is estimated, month is accurate, year is unknown",
      "eea - day and month are estimated, year is accurate",
      "eee - day, month and year are estimated",
      "eeu - day and month are estimated, year is unknown",
      "eua - day is estimated, month is unknown, year is accurate",
      "eue - day is estimated, month is unknown, year is estimated",
      "euu - day is estimated, month and year are unknown",
      "uaa - day is unknown, month and year are accurate",
      "uae - day is unknown, month is accurate, year is estimated",
      "uau - day is unknown, month is accurate, year is unknown",
      "uea - day is unknown, month is estimated, year is accurate",
      "uee - day is unknown, month and year are estimated",
      "ueu - day is unknown, month is estimated, year is unknown",
      "uua - day and month are unknown, year is accurate",
      "uue - day and month are unknown, year is estimated",
      "uuu - day, month and year are unknown"
    ]
}