schema = {
    "type": "string",
    "$id": "#country",
    "enum": [
          "adelie land (france)",
          "afghanistan",
          "aland islands",
          "albania",
          "algeria",
          "americas",
          "andorra",
          "angola",
          "anguilla",
          "antarctica",
          "antigua and barbuda",
          "argentina",
          "argentinian a t",
          "armenia",
          "aruba",
          "australia",
          "australia (includes e t)",
          "australian antarctic territory",
          "australian e t, nec",
          "austria",
          "azerbaijan",
          "bahamas",
          "bahrain",
          "bangladesh",
          "barbados",
          "belarus",
          "belgium",
          "belize",
          "benin",
          "bermuda",
          "bhutan",
          "bolivia",
          "bonaire, sint eustatius & saba",
          "bosnia and herzegovina",
          "botswana",
          "brazil",
          "british antarctic territory",
          "brunei darussalam",
          "bulgaria",
          "burkina faso",
          "burundi",
          "cambodia",
          "cameroon",
          "canada",
          "cabo verde",
          "caribbean",
          "cayman islands",
          "central african republic",
          "central america",
          "central and west africa",
          "central asia",
          "chad",
          "chile",
          "chilean antarcticterritory",
          "china (excludes sars & taiwan)",
          "chinese asia (incl mongolia)",
          "colombia",
          "comoros",
          "congo, democratic republic of",
          "congo, republic of",
          "cook islands",
          "costa rica",
          "cote d'ivoire",
          "croatia",
          "cuba",
          "curacao",
          "cyprus",
          "czech republic",
          "denmark",
          "djibouti",
          "dominica",
          "dominican republic",
          "eastern europe",
          "ecuador",
          "egypt",
          "el salvador",
          "england",
          "equatorial guinea",
          "eritrea",
          "estonia",
          "ethiopia",
          "faroe islands",
          "falkland islands",
          "fiji",
          "finland",
          "france",
          "french guiana",
          "french polynesia",
          "gabon",
          "gambia",
          "gaza strip and west bank",
          "georgia",
          "germany",
          "ghana",
          "gibraltar",
          "greece",
          "greenland",
          "grenada",
          "guadeloupe",
          "guam",
          "guatemala",
          "guernsey",
          "guinea",
          "guinea-bissau",
          "guyana",
          "haiti",
          "holy see",
          "honduras",
          "hong kong (sar of china)",
          "hungary",
          "iceland",
          "india",
          "indonesia",
          "iran",
          "iraq",
          "ireland",
          "isle of man",
          "israel",
          "italy",
          "jamaica",
          "japan",
          "japan and the koreas",
          "jersey",
          "jordan",
          "kazakhstan",
          "kenya",
          "kiribati",
          "korea, dem rep of (north)",
          "korea, republic of (south)",
          "kosovo",
          "kuwait",
          "kyrgyzstan",
          "laos",
          "latvia",
          "lebanon",
          "lesotho",
          "liberia",
          "libya",
          "liechtenstein",
          "lithuania",
          "luxembourg",
          "macau (sar of china)",
          "madagascar",
          "mainland south-east asia",
          "malawi",
          "malaysia",
          "maldives",
          "mali",
          "malta",
          "maritime south-east asia",
          "marshall islands",
          "martinique",
          "mauritania",
          "mauritius",
          "mayotte",
          "melanesia",
          "mexico",
          "micronesia",
          "micronesia, fed states of",
          "middle east",
          "moldova",
          "monaco",
          "mongolia",
          "montenegro",
          "montserrat",
          "morocco",
          "mozambique",
          "myanmar",
          "namibia",
          "nauru",
          "nepal",
          "netherlands",
          "new caledonia",
          "new zealand",
          "nicaragua",
          "niger",
          "nigeria",
          "niue",
          "norfolk island",
          "north africa",
          "north africa and middle east",
          "north-east asia",
          "north-west europe",
          "northern america",
          "northern europe",
          "northern ireland",
          "northern mariana islands",
          "norway",
          "oceania and antarctica",
          "oman",
          "pakistan",
          "palau",
          "panama",
          "papua new guinea",
          "paraguay",
          "peru",
          "philippines",
          "pitcairn islands",
          "poland",
          "polynesia (excludes hawaii)",
          "polynesia (excl hawaii), nec",
          "portugal",
          "puerto rico",
          "qatar",
          "queen maud land (norway)",
          "reunion",
          "romania",
          "ross dependency (new zealand)",
          "russian federation",
          "rwanda",
          "sint maarten (dutch part)",
          "st barthelemy",
          "st helena",
          "st kitts and nevis",
          "st lucia",
          "st martin (french part)",
          "st pierre and miquelon",
          "st vincent and the grenadines",
          "samoa",
          "samoa american",
          "san marino",
          "sao tome and principe",
          "saudi arabia",
          "scotland",
          "senegal",
          "serbia",
          "seychelles",
          "sierra leone",
          "singapore",
          "slovakia",
          "slovenia",
          "solomon islands",
          "somalia",
          "south africa",
          "south america",
          "south america, nec",
          "south-east asia",
          "south eastern europe",
          "south sudan",
          "southern and central asia",
          "southern and east africa",
          "southern and east africa, nec",
          "southern and eastern europe",
          "southern asia",
          "southern europe",
          "spain",
          "spanish north africa",
          "sri lanka",
          "sub-saharan africa",
          "sudan",
          "suriname",
          "swaziland",
          "sweden",
          "switzerland",
          "syria",
          "taiwan",
          "tajikistan",
          "tanzania",
          "thailand",
          "the former yugoslav republic of macedonia",
          "timor-leste",
          "togo",
          "tokelau",
          "tonga",
          "trinidad and tobago",
          "tunisia",
          "turkey",
          "turkmenistan",
          "turks and caicos islands",
          "tuvalu",
          "uganda",
          "ukraine",
          "united arab emirates",
          "uk, channel is and isle of man",
          "united states of america",
          "uruguay",
          "uzbekistan",
          "vanuatu",
          "venezuela",
          "vietnam",
          "virgin islands, british",
          "virgin islands, united states",
          "wales",
          "wallis and futuna",
          "western europe",
          "western sahara",
          "yemen",
          "zambia",
          "zimbabwe",
          "inadequately described",
          "at sea",
          "not stated"
      
    ]
}